### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ghost**
I have added more context in the readme

### CODE REVIEW

**Comment by nhcarrigan** [comment]
Hey there,

Thanks for taking the time to create this pull request. I think, rather than adding information here in the README, we should take advantage of the `docs` directory being hosted as the single source of truth, so we do not have to maintain information in two different locations. Thoughts?

**Comment by PulkitSinghDev** [comment]
yeah it's a nice idea but what if someone browses through this repo, at least they should get some info about this repo through the Readme at the time they just open this repo

**Comment by nhcarrigan** [comment]
Maybe the README can consist only of a link to the documentation, then

**Comment by PulkitSinghDev** [comment]
but previewing a small part of the repo at least, I guess was a better idea but it's up to you

**Comment by raisedadead** [comment]
Thank you for opening this pull request.

This is a standard message notifying you that we’ve reviewed your pull request and have decided not to merge it. We would welcome future pull requests from you.

Please read our [Guidelines for Contributing](https://contribute.freecodecamp.org) for more.

Thank you and happy coding.

**Pull request closed without merging**
